ALTER TABLE "ReadingPlan"
ADD COLUMN "finishedAt" TIMESTAMP(3);

CREATE TABLE "UserSettings" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "monHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "tueHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "wedHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "thuHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "friHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "satHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "sunHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
  CONSTRAINT "UserSettings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "UserSettings_userId_key" ON "UserSettings"("userId");

ALTER TABLE "UserSettings"
ADD CONSTRAINT "UserSettings_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
